### ISSUE TITLE
New line is inserted when saving the file while some text is selected

### ISSUE THREAD

**Issue by saneef** [candid82/sublime-pretty-clojure#3]
It's a weird problem. While saving the file (using <kbd>Cmd</kbd>+<kbd>s</kbd>) the subsequent text after selection is moved to the next.

<img src="https://user-images.githubusercontent.com/81863/102975456-1f3b8400-4526-11eb-8167-660e1a470c24.gif" alt="Screen grab of the problem" width="480"/>

Sublime Text: v3.2.2 b3211 (macOS)

**Comment by saneef** [comment]
I also tried with disabling plugins which may alter the view, like "TabNine", "BracketHighlighter",.... The problem remains.

**Comment by candid82** [comment]
This is because it tries to format the selected text only. This is a bit confusing, so I changed it to always format the entire file unless "format_selected" option is set to true: https://github.com/candid82/sublime-pretty-clojure/commit/3276fe8e7309481d8b5877690aa909c3f46b0d6c

Btw, what color scheme and font are these?

**Comment by saneef** [comment]
Thanks @candid82! 

I'm using Solarized - Light ([with some changes](https://github.com/saneef/Solarized)) together [Recursive Mono - Duotone](https://www.recursive.design) fonts.
